# Generated by Django 5.1.7 on 2025-03-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('category', models.IntegerField(default=1)),
                ('regTime', models.DateTimeField(auto_now_add=True)),
                ('hasConfirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user_info',
                'verbose_name_plural': 'user_info',
                'db_table': 'user_info',
                'ordering': ['regTime'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('regTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinfo')),
            ],
            options={
                'verbose_name': 'confirm.html-code',
                'verbose_name_plural': 'confirm.html-code',
                'db_table': 'confirm_code',
                'ordering': ['regTime'],
            },
        ),
    ]
