# Generated by Django 5.1.7 on 2025-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('category', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
